---
# tasks file for local-env-additions
- block:

  - group: name=atmosphere state=present

  - name: add ATMOSPHERE_GROUP_USERS to "atmosphere" group
    user: name={{ item }} group=atmosphere
    with_items: "{{ ATMOSPHERE_GROUP_USERS }}"

  - name: change group group permissions for "{{ APP_BASE_DIR }}"
    file: path={{ APP_BASE_DIR }} group=atmosphere mode="g+rwx" recurse=yes

  when: "{{ VAGRANT }}"